name: Another Workflow
on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Invoke Deployment
        uses: ./.github/workflows/base.yml  # Use relative path to the workflow
        env:
          VERSION: ${{ github.run_number }}
