name: Another Workflow
on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Invoke Base Workflow
        uses: ./.github/workflows/base.yml  # This is incorrect for workflows
        with:
          # You can pass inputs here if your base.yml accepts inputs
          version: ${{ github.run_number }}  # This should match the input expected by base.yml
