name: Another Workflow
on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  deploy:
    uses: shubhamchav/20.Reusing_Workflow/.github/workflows/base.yml@main  # Reference the reusable workflow at the job level
    with:
      VERSION: ${{ github.run_number }}  # Pass parameters via 'with'
