name: Another Workflow
on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  deploy:
    uses: ${{ github.repository }}.github/workflows/base.yml@${{ github.ref_name }}  # Dynamic reference to the reusable workflow with branch
