name: Another Workflow
on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  deploy:
    uses: ${{ env.REPO_PATH }}.github/workflows/base.yml@master

env:
  REPO_PATH: shubhamchav/20.Reusing_Workflow/
