name: Another Workflow
on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}  # Define the output for use
    steps:
      - name: Set environment
        id: set-env
        run: echo "::set-output name=environment::your_environment_value"

  prerequisite:
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - name: Prerequisite step
        run: echo "Running prerequisite"

  get-computer-name:
    runs-on: ubuntu-latest
    needs: prerequisite
    steps:
      - name: Get computer name
        run: echo "Computer name"

  copy-from-s3:
    runs-on: ubuntu-latest
    needs: get-computer-name
    steps:
      - name: Copy from S3
        run: echo "Copying from S3"

  deployment:
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    needs: [set-environment, prerequisite, get-computer-name, copy-from-s3]
    uses: shubhamchav/20.Reusing_Workflow/.github/workflows/base.yml@master
    with:
      environment: ${{ needs.set-environment.outputs.environment }}  # Pass the environment as an input if required
