name: Another Workflow
on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Invoke Deployment
        uses: ./${{ github.event.repository.name }}/.github/workflows/base.yml
        env:
          VERSION: ${{ github.run_number }}
