name: Another Workflow
on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  deploy:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Reusable Workflow
        uses: shubhamchav/20.Reusing_Workflow/.github/workflows/base.yml@master
