name: Another Workflow
on:
  push:
    branches:
      - master

env:
  REPO_OWNER: shubhamchav
  REPO_NAME: 20.Reusing_Workflow

jobs:
  deploy:
    uses: ${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}.github/workflows/base.yml@master  # Dynamic reference to the reusable workflow
