name: Another Workflow
on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Current Directory
        run: pwd  # This will print the current working directory

      - name: List Files
        run: ls -la  # This will list all files and directories in the current directory

      - name: Invoke Deployment
        uses: shubhamchav/20.Reusing_Workflow/.github/workflows/base.yml@master  # Replace with your actual repository details
        with:
          VERSION: ${{ github.run_number }}  # Pass parameters via 'with'
