name: Another Workflow
on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  checkout:
    uses: shubhamchav/20.Reusing_Workflow/.github/workflows/base.yml@master

  run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
