name: Base Workflow
on:
  workflow_call:  # This allows the workflow to be called by other workflows

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
