# .github/workflows/deployment.yaml
name: Base Workflow
on:
  workflow_call:  # This allows the workflow to be called by other workflows
    inputs:
      VERSION:
        required: true  # Make it required
        type: string  # Specify the input type
      ENVIRONMENT:
        required: true  # Make it required
        type: string  # Specify the input type

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print Current Directory
        run: pwd  # This will print the current working directory

      - name: List Files
        run: ls -la  # This will list all files and directories in the current directory

      - name: Build Step
        run: echo "Building version ${{ inputs.VERSION }} for environment ${{ inputs.ENVIRONMENT }}"  # Use the input variables
